/*
 * This file was automatically generated by EvoSuite
 * Fri Jul 03 12:09:46 GMT 2015
 */

package com.epam.tour.dao;

import com.epam.tour.entity.Role;
import com.epam.tour.entity.User;
import org.junit.Test;

import static org.junit.Assert.assertFalse;
import static org.junit.Assert.fail;

public class ClientDAO_ESTest  {

  @Test
  public void test0()  throws Throwable  {
      User user0 = new User();
      Role role0 = new Role();
      user0.setRole(role0);
      // Undeclared exception!
      try {
        ClientDAO.isRegularClient(user0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // StringEquals is not supposed to work on a null caller
         //
      }
  }

  @Test
  public void test1()  throws Throwable  {
      boolean boolean0 = ClientDAO.isRegularClient((User) null);
      assertFalse(boolean0);
  }
}
