/*
 * This file was automatically generated by EvoSuite
 * Fri Jul 03 11:57:02 GMT 2015
 */

package com.epam.tour.command;

import com.epam.tour.entity.User;
import org.junit.Test;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletRequestWrapper;

import static org.junit.Assert.assertTrue;
import static org.junit.Assert.fail;

public class LoginCommand_ESTest  {

  @Test
  public void test0()  throws Throwable  {
      LoginCommand loginCommand0 = new LoginCommand();
      HttpServletRequest httpServletRequest0 = null;
      HttpServletRequestWrapper httpServletRequestWrapper0 = null;
      try {
        httpServletRequestWrapper0 = new HttpServletRequestWrapper(httpServletRequest0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Request cannot be null
         //
      }
  }

  @Test
  public void test1()  throws Throwable  {
      LoginCommand loginCommand0 = new LoginCommand();
      // Undeclared exception!
      try {
        loginCommand0.execute((HttpServletRequest) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test
  public void test2()  throws Throwable  {
      LoginCommand loginCommand0 = new LoginCommand();
      User user0 = new User();
      boolean boolean0 = loginCommand0.checkAccess(user0);
      assertTrue(boolean0);
  }
}
