/*
 * This file was automatically generated by EvoSuite
 * Fri Jul 03 12:17:03 GMT 2015
 */

package com.epam.tour.command.client;

import com.epam.tour.entity.Role;
import com.epam.tour.entity.User;
import org.junit.Test;

import javax.servlet.http.HttpServletRequest;

import static org.junit.Assert.assertFalse;
import static org.junit.Assert.fail;

public class AccountCommand_ESTest  {

  @Test
  public void test0()  throws Throwable  {
      AccountCommand accountCommand0 = new AccountCommand();
      // Undeclared exception!
      try {
        accountCommand0.execute((HttpServletRequest) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test
  public void test1()  throws Throwable  {
      AccountCommand accountCommand0 = new AccountCommand();
      boolean boolean0 = accountCommand0.checkAccess((User) null);
      assertFalse(boolean0);
  }

  @Test
  public void test2()  throws Throwable  {
      AccountCommand accountCommand0 = new AccountCommand();
      User user0 = new User();
      Role role0 = new Role();
      user0.setRole(role0);
      // Undeclared exception!
      try {
        accountCommand0.checkAccess(user0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // StringEquals is not supposed to work on a null caller
         //
      }
  }
}
